### PR TITLE
CotE spoilers

### PR DESCRIPTION
**Pull request by jamesoddy**
Includes PR #75

### CODE REVIEW

**Comment by jamesoddy** [comment]
Presumably the failure in the build is because of the duplicate Totori name?  I'd heard on the grapevine that the id would be akodo-totori-2 but it looks as though the name cannot be duplicated as well.  Please advise.

**Comment by jamesoddy** [comment]
Also, where do we stand with the "French" spoilers?  http://www.fantasyflightgames.fr/jeux/article/la_legende_des_cinq_anneaux_lcg/les_enfants_de_lempire

Are they ok to bring in?  Translated ofc

**Comment by NoahTheDuke** [comment]
I wrote this on the other PR, but I'll include it here:

To make a new expansion, you need a few things:
1. the individual card files in `Card/`, named for their `"id"`
2. the cycle listed in `Cycle/` at the bottom
3. the specific release file in `PackCard/`, name for the `"id"` of that release.

The first should have all of the card rules stuff: name, mil and pol, text, traits, etc. The second should just have the name and release date and ffg id and size. The third should list every card in the release in release/pack order, with all of the non-rules stuff: flavor, illustrator, a url for the image, and the quantity included in the release.

Without all 3 pieces, it won't display right.

**Comment by Fuzzylog1cza** [comment]
French spoilers are OK to bring in.

**Comment by jamesoddy** [comment]
Hopefully this should be everything required for the spoilers.

NB: The PackCard file children-of-the-empire.json I have just put in a skeleton of the spoilers so far.  I have not added illustrators or flavor text, partly because I cannot get that information from some of the cards because of the quality of the image (or it's only a partial image).  I am also not sure of the position field because of the same reasons - I'm not sure how important that is.

**Pull request merged**
