### PR TITLE
Update data using cardgamedb

### PR DESCRIPTION
**Pull request by dlrowb**
see also -http://www.cardgamedb.com/index.php/legendofthe5rings/legend_of_the_five_rings

Fix some minor typos and add properties (position, illustrator and flavor).
I've also verified values (e.g. military, political, cost, glory...).

### CODE REVIEW

**Comment by Alsciende** [comment]
Thank you!

**Comment by Alsciende** [comment]
Oh no! The data is managed differently in fiveringsdb than in the previous repositories. The flavor, artist, and position keys are in PackCards, not in Pack.

If you can process your file automatically to move these properties to PackCards/core.json instead, I let you do it. Otherwise, I'll accept your PR and move them myself.

**Comment by dlrowb** [comment]
I'm sorry for bothering you.
I've reverted and add flavor texts to PackCard/core.json, but that makes conflicts.

Would you resolve conflicts and merge this commit? or I prepared auto mergeable branch (https://github.com/dlrowb/fiveringsdb-data/tree/to_merge_update_data_using_cardgamedb) so that I'll create new PR instead of this PR.

**Comment by Alsciende** [comment]
It's ok, I merged your other branch. Thank you very much!

**Pull request closed without merging**
